#!/bin/sh /etc/rc.common

USE_PROCD=1
START=99
STOP=10

CONF="luci-nexttrace"
LOG="/tmp/log/nexttrace.log"
PROG="/usr/bin/nexttrace"


start_service() {
    config_load "$CONF"

    local enabled
	config_get_bool enabled "config" "enabled" '0'
    [ "$enabled" -eq "1" ] || return 1

    local listen_addr
    config_get listen_addr "config" "listen_addr" '0.0.0.0:1080'


    procd_open_instance "$CONF"

    procd_set_param command /bin/sh -c "$PROG --deploy --listen $listen_addr > $LOG" 

    procd_set_param limits core="unlimited"
    procd_set_param limits nofile="65536 65536"
    procd_set_param respawn
    procd_set_param stderr 1

    procd_close_instance

}

service_triggers() {
	procd_add_reload_trigger "$CONF"
}

stop_service() {
    echo '' > "$LOG"
    return 0
}

reload_service()
{
    stop
    start
}